name: data_contract_experiments

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - ipykernel
  - pandas
  - scipy
  - jupyterlab
  - pip
  - git
  - pip: 
    - git+git://github.com/sergegoussev/datacontract-cli.git